version: '2.5'
services: 
          ubuntuimage:
                      container_name: mycontainer
                      build:
                            context: .
                            dockerfile: Dockerfile
                      ports:
                      - "8000:8000"
                      env_file:
                      - .env 
                      volumes:
                      - .:/app